/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.CompraData;
import AccesoADatos.ProductoData;
import AccesoADatos.ProveedorData;
import Entidades.Compra;
import Entidades.Producto;
import Entidades.Proveedor;
import java.awt.Graphics;
import java.awt.Image;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class Compras extends javax.swing.JInternalFrame {
    ImagenFondo fondo=new ImagenFondo();
   private ArrayList<Proveedor> listaP;
    private  ProductoData proData;
    private ArrayList<Producto> listapro;
     private  ProveedorData proveeData;
      private CompraData compData=new CompraData();
      private Compra compraActual=null;
    
    
   
    
//    private Compra compraActual=null;
    
    
    
    public Compras() {
       this.setContentPane(fondo);
        initComponents();
         proveeData= new ProveedorData();
         listaP= (ArrayList<Proveedor>)proveeData.obtenerProveedoresActivos();
         cargaIdProveedor();
         proData= new ProductoData();
         listapro=(ArrayList<Producto>)proData.listarProducto();
         cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JCBProveedor = new javax.swing.JComboBox<>();
        JCBProducto = new javax.swing.JComboBox<>();
        JTCantidad = new javax.swing.JTextField();
        JBGuardarCompra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JDCCompra = new com.toedter.calendar.JDateChooser();

        setTitle("Compra a Proveedores");

        JCBProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBProveedorActionPerformed(evt);
            }
        });

        JCBProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBProductoActionPerformed(evt);
            }
        });

        JTCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTCantidadActionPerformed(evt);
            }
        });

        JBGuardarCompra.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        JBGuardarCompra.setForeground(new java.awt.Color(255, 0, 153));
        JBGuardarCompra.setText("Confirmar Compra");
        JBGuardarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBGuardarCompraActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione Proveedor");

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione Producto");

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad:");

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Indique fecha de Compra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(JBGuardarCompra)
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCBProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCBProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JDCCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JCBProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JCBProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(JTCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JDCCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(JBGuardarCompra)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTCantidadActionPerformed

    private void JBGuardarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBGuardarCompraActionPerformed
         try{
        Proveedor idProveedor=(Proveedor)JCBProveedor.getSelectedItem();
        Producto idProducto=(Producto)JCBProducto.getSelectedItem();
        Integer cantidad=Integer.parseInt(JTCantidad.getText());
        java.util.Date cfecha=JDCCompra.getDate();
       LocalDate fechaCompra=cfecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
       
//        if (cantidad.isEmpty()){
//            JOptionPane.showMessageDialog(this, "Debe ingresar una cantidad valida");
//            return;
//            }
        
        if (compraActual==null){
            
          compraActual= new Compra (idProveedor, idProducto, cantidad, fechaCompra);
        compData.guardarCompra(compraActual);
       
         }else {
//            compraActual.setIdProveedor(idProveedor);
//            compraActual.setidProducto(idProducto);
//            compraActual.setCantidad(cantidad);
//            compraActual.setFechaCompra(fechaCompra);
//            compData.modificarCompra(compraActual);
        } 
             
          }catch(NumberFormatException nfe){
         JOptionPane.showMessageDialog(this,"Verifique los datos ingresados");           
            
                      
        
        }
        
       //limpiarCampos();
        
//            }
//            JOptionPane.showMessageDialog(this, "Compra realizada con exito");
//            
//                                                   
//         }
                                                   
    }//GEN-LAST:event_JBGuardarCompraActionPerformed

    private void JCBProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBProveedorActionPerformed
//           
    }//GEN-LAST:event_JCBProveedorActionPerformed

    private void JCBProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBProductoActionPerformed

     private void cargaIdProveedor(){
        for(Proveedor item: listaP){
            JCBProveedor.addItem(item);
        }
     }
     private void cargarProductos(){
          for(Producto item: listapro){
            JCBProducto.addItem(item);
        }
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBGuardarCompra;
    private javax.swing.JComboBox<Producto> JCBProducto;
    private javax.swing.JComboBox<Proveedor> JCBProveedor;
    private com.toedter.calendar.JDateChooser JDCCompra;
    private javax.swing.JTextField JTCantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

     
    
        
    
       
        
    

    
    
    
    
    
    class ImagenFondo extends JPanel{
     private Image imagen;
     
     public void paint(Graphics g){
         imagen=new ImageIcon(getClass().getResource("/Vistas/imagenes/panel.jpg")).getImage();
         g.drawImage(imagen,0,0,getWidth(), getHeight(), this);
        setOpaque(false);
         super.paint(g);
         
        }
 }


        }
        
